### ISSUE TITLE
[Supply Chain Disruption Notifications KIT] Missing gallery image 

### ISSUE THREAD

**Issue by jSchuetz88** [eclipse-tractusx/eclipse-tractusx.github.io#1008]
Currently the Supply Chain Disruption Notifications KIT misses the gallery image (see screenshot) is missing, as the image does not exist.
![image](https://github.com/user-attachments/assets/987dd1b9-c582-4dad-98b3-ed20f1cbf681)

### Current Behavior
No gallery image is shown.

### Expected Behavior
Gallery image is shown.

### Steps To Reproduce
See section "Our Kits": https://eclipse-tractusx.github.io

**Comment by jSchuetz88** [comment]
CC: @dominikoeh

**Comment by jSchuetz88** [comment]
@tom-rm-meyer-ISST I had a hand over with @maximilianong and can try to create one. I was not sure, whether there is already one.

**Comment by tom-rm-meyer-ISST** [comment]
> @tom-rm-meyer-ISST I had a hand over with @maximilianong and can try to create one. I was not sure, whether there is already one.

Ah sorry, then thanks a lot!

**Comment by jSchuetz88** [comment]
@tom-rm-meyer-ISST maybe something like that? 
![image](https://github.com/user-attachments/assets/145826ca-ce36-4edc-8f5f-887cfad4da11)
If you prefer different colors, icons and / or short description, I can change it

**Comment by tom-rm-meyer-ISST** [comment]
Thanks a lot! I would do the following adjustments:
- `!` schould be in a speech buble instead of the kaboom bubble, same as for traceability and I would put it to the upper right instead of lower right (similar to sustainability)
- color should be some kind of pink or purple because the Business Domain Resiliency / PQR Committee has these colors.
- Text "Inform partners about disruptions in the supply chain".

**Comment by jSchuetz88** [comment]
![image](https://github.com/user-attachments/assets/ec55fe80-7102-4e7c-af7d-c8a8b72e58ff)

**Comment by tom-rm-meyer-ISST** [comment]
Both Look great, I would go for the right one, but align the speech buble to the same style (not round but rounded corners) as in traceability (common CI / look and feel).

Are you creating the PR? That way we can get it in quickly (second committer at hand).

**Comment by jSchuetz88** [comment]
PR to close this issue: #1015
