### ISSUE TITLE
Propose TRG for product deprecation

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#1037]
https://github.com/orgs/eclipse-tractusx/security/overview

Ask committers to fix it, and give a deadline.

Take to the committer meeting.

---
Update Sep. 25 ⇾ regular topic in committer meeting ⇾ How much time do we give the committer to solve the problems? ⇒ New TRG proposal by Tom Meyer

---

Update Oct 2: Tom created https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1045, please review until next week

---

Update Oct 9: PR Review in Progess, will be discussed in Committer Meeting from Oct. 11 https://github.com/orgs/eclipse-tractusx/projects/61/views/6?pane=issue&itemId=79712658

**Comment by matbmoser** [comment]
@tom-rm-meyer-ISST I will support you as much as I can
