### ISSUE TITLE
integrate external md files in Data Chain Kit

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/eclipse-tractusx.github.io#107]
Please add the external resources in the Data Chains Kit under documentation: 
- https://eclipse-tractusx.github.io/item-relationship-service/docs/arc42/
- https://raw.githubusercontent.com/eclipse-tractusx/item-relationship-service/gh-pages/docs/administration/

**Comment by santiagoejm** [comment]
Hi @jzbmw, please send me the link to the folder/s of the item-relationship-service repo where those .mds are (not the gh-page), I've tried to find them but no luck so far; and the second link is broke, it's pointing to a raw gh-pages folder.

Cheers
