### ISSUE TITLE
Add versioning function

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#113]
We would like to add the versioning function provided by Docusaurus to **relevant docs or pages.**

- Version dropdown in the header navigation
- Version pill / information above the doc / page content

<img width="574" alt="Bildschirmfoto 2023-02-03 um 15 29 38" src="https://user-images.githubusercontent.com/83761111/216629113-dbc926f0-fb1a-4cba-8f75-73a0c1bf6bfa.png">
<img width="179" alt="Bildschirmfoto 2023-02-03 um 15 29 24" src="https://user-images.githubusercontent.com/83761111/216629122-25ed6077-2759-461a-bfbe-a108a795db07.png">

**Comment by stephanbcbauer** [comment]
@maximilianong I like. And I think we need it, maybe “differently”. Please have a look #181

**Comment by maximilianong** [comment]
@santiagoejm is working on that. WIP.
