### ISSUE TITLE
Check if the news slider can automatically display the last 3 news from the news blog

### ISSUE THREAD

**Issue by danielmiehle** [eclipse-tractusx/eclipse-tractusx.github.io#115]

**Comment by maximilianong** [comment]
@santiagoejm is this done? If not, would be nice if you can prepare this for our next review session - thanks.

**Comment by maximilianong** [comment]
It is not possible to do it automatically - we need to do it manually. 
Documentation is available: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-Update-the-News-page-by-adding-a-new-post%3F
