### ISSUE TITLE
AUTHORS.md link broken in TRG2.03

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io#117]
The AUTHORS.md example file referenced in release guideline TRG2.03 link is broken. It points to a .md file, but the file itself is present as .txt

**Comment by FaGru3n** [comment]
Inthink that @carslen already fixed the Typo

**Comment by carslen** [comment]
Typo was fixed, but the link is broken, True.
