### ISSUE TITLE
Fix path in Data Chain Kit documentation

### ISSUE THREAD

**Issue by neischlah** [eclipse-tractusx/eclipse-tractusx.github.io#146]
Hi everyone,

I tried following this documentation:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/17e95639b5c176d0afc97f0c7d9c899edc15f03a/docs/kits/Data%20Chain%20Kit/page_software-operation-view.md

However, I'm stuck at step 3 as I can't find the described path in the IRS repo.

Thanks!

**Comment by jzbmw** [comment]
@neischlah We already work on that issue.

**Comment by jzbmw** [comment]
Hi @neischlah, 
I've updated the information on the page. Feel free to try that out. If you have any feedback, get in touch with me or @mkanal.
