### ISSUE TITLE
Add Comment to Autogenerated Files

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/eclipse-tractusx.github.io#186]
As discussed in the review of #182, the API documentation of the KITs is generated via the docusaurus `gen-api-docs` plugin (see [this GitHub repository](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs)). To prevent misunderstandings, as suggested by @Siegfriedk, a comment should be added to every auto-generated file indicating that it isn't written manually by a human.

One example of such a comment could be:
```
<!-- ----------------------------------------------------------------------------------------------
    WARNING: THIS FILE IS AUTO-GENERATED!
    Don't edit this page manually. Use docusaurus gen-api-docs to generate it.
----------------------------------------------------------------------------------------------- -->
```

**Comment by maximilianong** [comment]
@mhellmeier we are going through each and every issue right now. Where have you added this warning already? Or is this just an example as a recommendation?
