### ISSUE TITLE
Handling Large Files for Documentation

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/eclipse-tractusx.github.io#195]
When working on documentation like the KITs, it is sometimes necessary to add explanation videos or tutorials as described [in the Tutorials section of the KIT Artefacts](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/KIT-Artefacts#tutorials-recommended).

By default, GitHub can only handle files up to 100.00 MB. Every bigger one falls under [large files](https://docs.github.com/en/repositories/working-with-files/managing-large-files).

What is the desired workflow to include large files, like videos?

**Comment by FaGru3n** [comment]
some suggestion
https://git-lfs.com/
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

**Comment by FaGru3n** [comment]
if you want to join the discussion with eclipse 
[Eclipse Matrix Chat](https://chat.eclipse.org/#/room/!DWDObjgSCMTOqevBVY:matrix.eclipse.org/$pI1yIfRDfwhwpFCWyq9CBirLFNcscnOclBddG0pBjJI?via=matrix.eclipse.org&via=matrix.org&via=digitale-gesellschaft.ch)

**Comment by FaGru3n** [comment]
@maximilianong: 
not at all heard of some example for a youtube channel form one of our Eclipse Foundation Members/ Leaders:
https://www.youtube.com/@waynebeaton8676

**Comment by FaGru3n** [comment]
> But is this really the "open source way"? :D @danielmiehle can you take this into your weekly call? I think this will become relevant. More and more videos are coming.

Catena-X does it allready maybe we can talk to the owner of the channel
https://www.youtube.com/channel/UCeD0sip1CiWtKp41oAZh1fg

**Comment by SebastianBezold** [comment]
Hi @maximilianong,

git is just not the tool to store large files like videos. There are better platforms for that (like Youtube). We would even need to separate association content from videos regarding our reference implementation in Eclipse Tractus-X.

If we want to continuously create video content, then we need to find someone, who would maintain such a channel.
In my opinion we can close this issue here, since embedding it in the git repo is not an option for me. Feel free to open a general discussion though to find other options

**Comment by maximilianong** [comment]
Hi @SebastianBezold 

We have now two conversations here running. I would like to merge them.

This one - lets go with YouTube or something else because Github ist not the right place.
The other one here: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/288 - Github supports large files. Maybe we should open a separate repository for them.

I like the second option more.

**Comment by SebastianBezold** [comment]
Hi @maximilianong,
I know, that git supports large files. But while this is __possible__ I personally think this is not __ideal__.
I would always vote for a streaming platform like Youtube for example. Did you investigate these possibilities?

**Comment by Siegfriedk** [comment]
As mentioned in the other PR:


Daniel asked me this question on Email and just adding it here in case this were two different things (pls close it if its solved):

Github supports Large Files and Github also tells us to use releases for referencing those files.
https://docs.github.com/en/repositories/working-with-files/managing-large-files

I would suggest to either use a second repository which only contains large files, releasing it and than referencing the file or releasing this repo and adding it here but this might get convoluted


@SebastianBezold those videos have very small download numbers (probably) the time and effort to manage a YouTube Channel is probably not worth it at all.

We should try to use github as they document and mention it and change this as soon as this creates an issue.

I still think its absolutly fine adding big files to git. There are plenty of other positive use cases and the existens of git lf is proof of this. The whole Huggingface ecosystem for example also uses this. Gitlab provides lf support to.

And it would be the EF Responsibility to create a YT Account as we don't have anything today on our side to manage accounts really.

**Comment by FaGru3n** [comment]
try to ask the Eclipse Foundation for a hint or advise:

[Eclipse Matrix Thread](https://chat.eclipse.org/#/room/!DWDObjgSCMTOqevBVY:matrix.eclipse.org/$gm-xraD90mj8XmDIYcnvHT6Rv4utEe6VRLJV1ILewzE?via=matrix.eclipse.org&via=matrix.org&via=rory.gay)

**Comment by danielmiehle** [comment]
Repo for large files created:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles

Please add a folder for your domain (e.g. Sustainability or Resiliency) and add your large files following the naming convention: DATE_KIT_TITLE_VERSION (e.g., 230808_ECOPASS_VIDEO_v1

**Comment by SebastianBezold** [comment]
The repo is not yet initialized to use Git LFT, so please do not just add files before this is done. 
Also, if we want to have naming conventions, these have to be documented. Best in the repo itself in the`REDME.md`

**Comment by SebastianBezold** [comment]
I added eclipse-tractusx/eclipse-tractusx.github.io.largefiles#1 and eclipse-tractusx/eclipse-tractusx.github.io.largefiles#2 to track when Git LFS is enabled and the naming convention documented.
