### ISSUE TITLE
Mistaking in writing Connector KIT

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#199]
On the tile of the connector kit is a mistake in writing.
Here is the new, corrected tile.
Please change it on the home page and on the kits page.

![Group 149](https://user-images.githubusercontent.com/83761111/233928708-9987d66e-f233-4efd-a2be-17f52b1e80a8.png)

**Comment by Siegfriedk** [comment]
@maximilianong can you pls close issues which are solved?
