### ISSUE TITLE
Link to TRG 5.09 not working

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/eclipse-tractusx.github.io#219]
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/629d057af08c5444b259b9b15be663599621f8af/docs/release/trg-5/trg-5-08.md?plain=1#L23

Link not working as expected in rendered website.

**Comment by Siegfriedk** [comment]
@carslen i tried it out and it does work for me. What do you see?

**Comment by carslen** [comment]
Mabe this is a docusaurus bug. If you initially open the TRG 5.08 page an follow the link to TRG 5.09 it'll work. If you press F5 on TRG 5.08 and follow then to TRG 5.09 you get "Page not found" according to malformed URL (`https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08/trg-5-09`):

![grafik](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/28647218/f297710e-0d35-4696-ac99-f5b439897d05)

**Comment by Siegfriedk** [comment]
Firrst of: i did check the wrong link. I verified helm test.

But you are right: As soon as the trg-5-08 gets an / at the end, the link to the trg 5.09 breaks. 

I will try to investigate, everyone else feel free to do so i'm not sure when i find the time.
