### ISSUE TITLE
Open API docs partly missing

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/eclipse-tractusx.github.io#233]
Currently, the business partner kit (@santiagoejm) has a [Pool API](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/docs/kits/Business%20Partner%20Kit/Software%20Development%20View/Pool%20Api) without an associated Open API yaml file in the `openApi` folder.

Similar to them, the data chain kit (@jzbmw) has a [Job API](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/docs/kits/Data%20Chain%20Kit/Software%20Development%20View/Job%20Api) without an associated Open API yaml file in the `openApi` folder.

To fix this issue, the missing files should be added to the `openApi` folder and added to the [`docusaurus.config.js`](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/docusaurus.config.js) for automated generation.

**Comment by santiagoejm** [comment]
Hi @mhellmeier, you are right the `Pool API` file is missing from the `openApi` folder (don't know when this happened), I can bring it back to the project using the `docusaurus-plugin-remote-content`. I guess you need to generate a lot of `openapi-docs` with the plugin and the `npm run docusaurus gen-api-docs ID` is not an option right?

@danielmiehle can you confirm that the [Pool API](https://raw.githubusercontent.com/eclipse-tractusx/bpdm/main/docs/api/pool.yaml) file hasn't changed and I can bring it back safely to the project to regenerate [all this endpoints](https://eclipse-tractusx.github.io/docs/kits/Business%20Partner%20Kit/Software%20Development%20View/Pool%20Api/business-partner-data-management-pool)?

**Comment by mhellmeier** [comment]
A much easier solution than triggering a full regeneration process is just by looking into the commit history. `git log --diff-filter=D --summary` will easily identify the two commits where the files were deleted:

BPDM Pool API: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/commit/0da5210e665b340b9b7296720cc7505ccfa04c7a
Data Chain Job API: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/commit/d96885ca7351d541aaf2b940a46f97a3538884b3
