### ISSUE TITLE
Data Chain Kit URL has wrong link

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/eclipse-tractusx.github.io#236]
When you select any main KIT in the navigation, all of them have proper links.

Data Chain Kit though references https://eclipse-tractusx.github.io/docs/sidebar which needs to be fixed

**Comment by maximilianong** [comment]
@jzbmw - will you have a look into this or should we take care?

**Comment by santiagoejm** [comment]
@maximilianong it's solved in PR #318, after merged you can close this issue as well :)

**Comment by maximilianong** [comment]
@danielmiehle merged it - thanks to @santiagoejm !
