### ISSUE TITLE
fail: Building failure

### ISSUE THREAD

**Issue by santiagoejm** [eclipse-tractusx/eclipse-tractusx.github.io#244]
Hi @Siegfriedk, the building of the page is failing generating this [error](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/runs/5046384759/jobs/9051820926), is produced in this [commit](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/commit/5fc7de9a24bdf3a98795d61757f72c8645054c68), in line 53 I notice the missing closing "/" for the `<br>` tag

**Comment by Siegfriedk** [comment]
@santiagoejm tx for the hint, i hadn't had enough time to analys it for way too long. 

Suggestion thouh: if you find an issue like this, you can also do a sort patch.
