### ISSUE TITLE
tractus-x: Please create new GH repository

### ISSUE THREAD

**Issue by zfdevzfdev** [eclipse-tractusx/eclipse-tractusx.github.io#265]
Hello, I'm a developer for ZF AG. We need a git repo for our new Quality FOSS app.

Please create a new GH repository in eclipse-tractusx GH organization:

GH Org: eclipse-tractusx

Repo Name: quality_app

GH Pages: Enabled

Priority: Medium
Severity: Normal

@sigi for approval

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev,

thanks for your issue 😃 
but i think this is not the right place to request a new repo in https://github.com/eclipse-tractusx

as mentioned in our documentation https://eclipse-tractusx.github.io/docs/oss/issues/#eclipse-foundation-helpdesk
[Example Request a new Repo in https://github.com/eclipse-tractusx](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2273) for requesting a new repository

also a bit explained in https://catenax-ng.github.io/docs/resources
