### ISSUE TITLE
Add last contributer/responsible person to each page/section 

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/eclipse-tractusx.github.io#266]
To boost the communication between user and developer we could add the gh-profile of the last contributer or the responsible person to each page displayed on the webpage. As example we thought of the profile displayed on the [news section](https://eclipse-tractusx.github.io/blog) of the tractus-website.

inital suggestion by @stephanbcbauer

**Comment by FaGru3n** [comment]
Hi @LuisRickert , 

cool idea and i think we already have a list of our working members. 
So basically i would just reference it to our Eclipse-Foundation page to prevent so many updates on the page for just replacing the last committer. (reduce workload on the actions to build the page)
https://projects.eclipse.org/projects/automotive.tractusx/who

Generally News Blogs are cool for the docusaurus page. As System Team member we also use it... https://catenax-ng.github.io/blog

**Comment by stephanbcbauer** [comment]
@FaGru3n maybe you can have a look here #298

**Comment by FaGru3n** [comment]
cool thanks for the input, then is would suggest seems a nice and informal idea to add the last contributor on the page and for questions there are at lease one person how you can talk to... ;)

**Comment by SebastianBezold** [comment]
Hi @FaGru3n and @stephanbcbauer ,
is this issue still relevant?

I'm not sure though, if this is a good thing on all pages. Most content is maintained by a group of people, I would expect. if we would start to add team names as authors, then it would again be hard to reach them. Could be mitigated by linking to a dedicated Matrix room, if that makes sense. 

A Docusaurus built in option to specify authors exists in the [last_update frontmatter option](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#last_update).
I would hope, that the `author:` property resolves to the ID in the `authors.yaml`, but we would need to try that out.

**Comment by arnoweiss** [comment]
I suggest to imply that the latest commit to a relevant file (like a kit's adoption view) is the respective owner. And to close this ticket.

**Comment by FaGru3n** [comment]
> I suggest to imply that the latest commit to a relevant file (like a kit's adoption view) is the respective owner. And to close this ticket.

with that i would close the issue, if further work should be added we can reopen the issue. 😉
