### ISSUE TITLE
Adding new KIT to top bar

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#276]
The docs contain (outdated but helpful) information on how to add a new KIT. Adding a section to sidebarsDocsKits.js adds it here:
![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/86715435/ecb520a6-4bb7-4f7e-8eac-9eed9755086c)
but not here:

![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/86715435/17d3f558-580c-44e5-916a-ef53d6a17063)

@santiagoejm - can you update the docs with the relevant info?

**Comment by santiagoejm** [comment]
Hi @arnoweiss, thank you for your comment. A full update of the documentation is coming soon, at the moment other urgent matters that are also gonna affect the documentation are been solved first, but if you need to know more right away about how to update the last shared item [here](https://docusaurus.io/docs/2.2.0/api/themes/configuration#navbar-dropdown) you can find the `Docusaurus` documentation.

In the code, you find it defined here -> `docusaurus.config.js`
![Screenshot 2023-06-26 at 12 44 18](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/68547995/79407b14-79e6-4092-a7a5-617e3ba8146d)

Hope it helps, Cheers!

**Comment by arnoweiss** [comment]
This works, thanks!
