### ISSUE TITLE
Release plan overview on tractusx webpage (developer hub)

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#282]
## WHAT
A release plan for the next planned releases (also with date) and components (kits, products) would be nice. PLant UML or Marmaid should be ok to create such a releasediagramm. Not sure how detailed it should be, but also milestones like qgates would be good.

## WHY
Would be good to get a better overview, cause right now there are different powerpointslides and a centralized diagramm would be resally helpfull

**Comment by stephanbcbauer** [comment]
Could be also “generated” via planning board and issues like https://github.com/orgs/eclipse-tractusx/projects/16 -> right now only the products are visible, but if we would work with milestones, it could be a whole release plan

**Comment by danielmiehle** [comment]
Done.

https://eclipse-tractusx.github.io/release-information

**Comment by stephanbcbauer** [comment]
Looks good. Thx
