### ISSUE TITLE
add additional questions to contribution page

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/eclipse-tractusx.github.io#283]
We want to extend the contribution FAQ by the following topics:

- [x] When to update
- [x] What to do if you want to change an already release cantena version
- [x] explain the general GIT Workflow
- [ ] What to do for a KIT Promotion
- [x] rename contribution page

**Comment by SebastianBezold** [comment]
HI @danielmiehle and @LuisRickert,

is this issue still relevant? If not, please close it
