### ISSUE TITLE
Large media files in docusaurus

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#288]
We'd love to embed some video tutorials in our KIT documentation. Referencing a video file in markdown should be easy. However uploading 100 MBs of video data to the repository would be bad. I think we need a video storage (like youtube?) where we can host the videos and then reference them.

What are your thoughts on this?

**Comment by Siegfriedk** [comment]
Daniel asked me this question on Email and just adding it here in case this were two different things (pls close it if its solved):

Github supports Large Files and Github also tells us to use releases for referencing those files.
https://docs.github.com/en/repositories/working-with-files/managing-large-files

I would suggest to either use a second repository which only contains large files, releasing it and than referencing the file or releasing this repo and adding it here but this might get convoluted

**Comment by maximilianong** [comment]
Hi 
there is another issue about pretty much the same topic - maybe we can move the discussion to this: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/195
