### ISSUE TITLE
[TRGs]: Add `distroless` as aligned allowed docker base image

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io#309]
## Description

`distroless` is a lightweight image, that can be used, if you want to just run a simple binary for example.
We need to collect the necessary information for the "Notice on docker images" and add it to the list of aligned images

**Comment by tomaszbarwicki** [comment]
Hi @SebastianBezold, do we still need that? Is distroless used anywhere by us?

**Comment by SebastianBezold** [comment]
Hi @tomaszbarwicki,
since this is not urgent, and I am not sure if there are publicly available container scan results, we can drop the issue for now and revisit, if it becomes relevant again.
I thought we had examples basing on distroless, but cannot find it ad-hoc
