### ISSUE TITLE
edc-tests helm chart repo details not available

### ISSUE THREAD

**Issue by rishabh-rdg** [eclipse-tractusx/eclipse-tractusx.github.io#311]
Trying to execute the command "helm install infra edc-tests/deployment/src/main/resources/helm/test-infrastructure --update-dependencies"

Error 1 - "Error: unknown flag: --update-dependencies"

If I remove "--update-dependencies" and try again.
Error 2 - "Error: INSTALLATION FAILED: repo edc-tests not found".

Reference link - https://eclipse-tractusx.github.io/docs-kits/kits/tractusx-edc/edc-tests/deployment/test-infrastructure/
In this link the repo details to be added to be able to execute this command are not available.

Similar details are present in other pages like -
![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/140103376/510b01c7-654f-43bf-9deb-4568f11b038c)

**Comment by maximilianong** [comment]
Hi @rishabh-rdg - maybe it makes sense to move this question to the direct repository of the tractus-x edc: https://github.com/eclipse-tractusx/tractusx-edc/discussions

**Comment by rishabh-rdg** [comment]
Hi,
I asked the same question in the TractusX EDC chat room, what I understand is this is an outdated document. So the issue is related to github.io page. This section should either be updated or removed if the steps mentioned here are no longer valid.

**Comment by carslen** [comment]
Section has been removed.
