### ISSUE TITLE
feat(tutorials): E2E tutorial Connector Kit - local playground

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/eclipse-tractusx.github.io#315]
**Description:**

We want to create a Terraform script to set up two TractusX EDCs, named Alice and Bob, along with their required PostgreSQL databases and HashiCorp Vaults. The deployment should utilize the related HelmChart for consistency. Additionally, Terraform should handle the configuration of port forwarding, routes, and any other necessary components. To ensure reusability, all configurations in Terraform should be done using variables.

**Documentation Task:**

The entire setup process must be thoroughly documented in a step-by-step manner. The documentation should cover the following aspects:

1. Prerequisites:
-  List all the prerequisites required to run the Terraform script successfully.
2. Tools and Further Documentation:
- Provide links to the necessary tools and any additional documentation required for the setup.
3. Terraform Script Usage:
- Detail how to use the Terraform script to bring up the TractusX EDCs, PostgreSQL databases, and HashiCorp Vaults.
4.  Example cURL Commands:
- Include example cURL commands with sample payloads to demonstrate how to add assets, policies, and contract definitions.
- Add relevant links, such as to the management API documentation.
5. Data Transfer between EDCs:
- Describe how to perform data transfers between the two EDCs after adding data to one of them.
- Provide prepared cURL commands for data transfer and consider linking the Postman collection if available.

**Goal of the Issue:**

The main objective of this issue is to create comprehensive documentation along with a prepared Terraform script. By following the documentation and utilizing the script, users should be able to set up a local running dataspace. This local dataspace will act as a playground, enabling users to gain a better understanding of dataspace, EDCs, and related data transfers.

**Comment by stefan-ettl** [comment]
Additional Tasks
0 - Setting the Scene
- [ ] Create a section with Introductory Sentences.
- [ ] Link to a proper Catena-X Introduction. (for example the 101 Docs?)
- [ ] Link to a Business Case.
- [ ] Build the bridge to the technical components.

**Comment by stephanbcbauer** [comment]
This issue can be closed because the tutorial with required content is already online https://eclipse-tractusx.github.io/docs/tutorials/e2e/
