### ISSUE TITLE
feat(tutorials): E2E tutorial Connector Kit - local playground with own edc

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/eclipse-tractusx.github.io#316]
**Description**

 

This is a documentation task aimed at providing a step-by-step guide for adding and registering a new TractusX EDC named Trudy within the local dataspace. The process involves utilizing the related HelmChart with PostgreSQL database and HashiCorp Vault. Additionally, the documentation should cover how to handle data transfer within the local dataspace.

 

Please note that although the registering process is more complex without the portal, it is essential for a better understanding of the TractusX EDC ecosystem.

 

**Documentation Tasks**

 

_The documentation should address the following tasks in a step-by-step manner, including necessary links, prerequisites, and other relevant information to enhance user understanding._

 

1. Configure the New TractusX EDC (Trudy):
    - Provide detailed instructions on how to configure the new TractusX EDC (Trudy).
    - Highlight the important properties and where to obtain the required information.
2. Run TractusX EDC (Trudy) in the Dataspace:
    - Explain the process of running TractusX EDC (Trudy) within the local dataspace.
    - Include any specific configurations or settings required for seamless integration.
3. Example cURL Commands for Data Management:
    - Provide a set of example cURL commands for adding assets, policies, and contract definitions to TractusX EDC (Trudy).
    - Include explanations and comments to aid users in understanding the purpose and usage of each command.
4. Testing Access Control Policies:
    - Describe how to create specific policies to test access control for TractusX EDC (Trudy).
    - Include scenarios where access may be granted or restricted between TractusX EDCs.

 

**Goal of the Issue**

 

The objective of this documentation task is to empower users to add and register a new TractusX EDC (Trudy) within their own local dataspace. The provided step-by-step guide, along with example cURL commands and testing scenarios, should enable users to successfully set up a fully running and working third TractusX EDC in their dataspace.

 

_Note: Please note that this issue does not involve code implementation but focuses solely on creating comprehensive documentation._

**Comment by stephanbcbauer** [comment]
This issue can be closed because the tutorial with required content is already online https://eclipse-tractusx.github.io/docs/tutorials/e2e/
