### ISSUE TITLE
Dead Link 

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/eclipse-tractusx.github.io#333]
The link to the Tractus-x linters is wrong. The affected page is this [one](https://eclipse-tractusx.github.io/docs/kit-process/processes/update-documentation). The link is located under the notes section at the bottom of the page.

**Comment by santiagoejm** [comment]
Hi @LuisRickert :) do you know where should that link point to? currently it looks like is trying to access a file in the `docs/kit-process/processes/` folder but with a bad ending afterwards: https://eclipse-tractusx.github.io/docs/kit-process/processes/%22https://github.com/eclipse-tractusx/eclipse-tractusx.github.io%22

However, in the `processes` folder there is no file that refers to the **linters**

**Comment by LuisRickert** [comment]
I think it should to the [readme](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/README.md) in the root directory, there are the linters mentioned or to implemented linter directly,[here](https://github.com/DavidAnson/markdownlint-cli2).

**Comment by santiagoejm** [comment]
Thank you @LuisRickert! What do you think @danielmiehle @maximilianong?

**Comment by santiagoejm** [comment]
As discussed the mentioned `Link` is been  removed of the `Notes` list

@LuisRickert can you close this issue?
