### ISSUE TITLE
Sidebar.js file for KIT documentation still neccessary?

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/eclipse-tractusx.github.io#335]
In the documentation on how to update documentation it is stated that it is necessary to have a sidebar.js within the documentation folder of the KIT. [Here](https://eclipse-tractusx.github.io/docs/kit-process/processes/update-documentation#schema).

I found multiple sidebar files in the root directory. 
- [sidebarsDocsKits](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/sidebarsDocsKits.js)
- [sidebarDocsProducts](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/sidebarsDocsProducts.js)
- [sidebar](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/sidebars.js)

Based on the existence of the files listed above i assume the documentation is outdated, if not this issue is futile.

**Comment by santiagoejm** [comment]
Hey @LuisRickert, indeed the `sidebar.js` file it is not defined in there, I'll remove it from the documentation
