### ISSUE TITLE
Carousel component for role based entry 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#348]
<img width="1125" alt="Bildschirm­foto 2023-08-21 um 10 17 05" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/83761111/0303bc5b-5501-4f3e-9857-919623c9f0d9">

Carousel component as shown in the image.
Behavior of this carousel should be similar to this example:
https://www.apple.com/supplier-responsibility/
Scroll down to the part after "More from Apple on our global supply chain."

MaterialUI example: https://react-slick.neostack.com

When mouse-over: change color of the background to #000000 (20%) + introvert the color of the arrow-button (same as the behavior of the other buttons on the page).

**Comment by carslen** [comment]
Please review the PR #387 I'm not sure if the PR handles your request properly (Lorem ipsum content?)
