### ISSUE TITLE
New enhanced text + image component

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#349]
<img width="1120" alt="Bildschirm­foto 2023-08-21 um 10 23 52" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/83761111/e77f0c46-82b5-4f9a-9a2c-f99a87fd18c1">

A new enhanced text + image component as shown in the image.
Image in the component and text is not clickable.
Button should be clickable and introverted on mouse-over (same behavior as other buttons on the existing page).

**Comment by manojava-gk** [comment]
<img width="1428" alt="Screenshot 2023-09-20 at 4 28 51 PM" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/111366021/c60e9297-0553-4589-8eed-4dc3d6aeaff0">
Attaching an image for your ref

**Comment by manojava-gk** [comment]
PR - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/405

**Comment by maximilianong** [comment]
Hi @manojava-gk , we reviewed the PR -

First line "Roadmap & Release" needs to changed to "Welcome to the community"
Please change the button text from "DevHub" to "About Us" and the link should go to /aboutus

**Comment by manojava-gk** [comment]
> About Us

PR updated
