### ISSUE TITLE
Grey carousel component for navigation

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#350]
<img width="1132" alt="Bildschirm­foto 2023-08-21 um 10 31 30" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/83761111/7ae79849-8d0e-4e87-9472-ca05891c2b94">

Carousel component as shown in the image.
Behavior of this carousel should be similar to this example:
https://www.apple.com/supplier-responsibility/
Scroll down to the part after "More from Apple on our global supply chain."

MaterialUI example: https://react-slick.neostack.com/

When mouse-over: change color of the background to #000000 (20%)

**Comment by maximilianong** [comment]
Hi @manojava-gk can we make the whole item clickable? Right now, only the link below the item is clickable (e.g. DevHub).

**Comment by manojava-gk** [comment]
> Hi @manojava-gk can we make the whole item clickable? Right now, only the link below the item is clickable (e.g. DevHub).

Easy one -> we just have to move <Link> tag to the parent container

**Comment by manojava-gk** [comment]
> > Hi @manojava-gk can we make the whole item clickable? Right now, only the link below the item is clickable (e.g. DevHub).
> 
> Easy one -> we just have to move tag to the parent container

PR - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/421
