### ISSUE TITLE
Change the current Release Cycle diagram with "something" which fits more to open source

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#352]
## Why

There is a release [cycle picture](https://eclipse-tractusx.github.io/release-information/#release-cycle), which is added as a picture and not as code (e.g. plant UML, mermaid). In this case, it is not possible to edit this release cycle without any knowledge about the sources.

We should be able to edit the diagramm directly with a PR. Mermaid could be an option

### Current picture

<img width="805" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/c3e84b6c-f478-40ff-8c7e-979ca54b1d9e">

### Created with mermaid

```mermaid
gantt
    title Next Release Cycles
    dateFormat  DD-MM-YYYY
    todayMarker off
    
    section Release v23.12
    Feature Definition           :a1, 15-07-2023, 07-08-2023
    Feature Enhancement 07/08/23 :milestone, after a1, 0d
    Feature Work                 :a2, 07-08-2023, 13-10-2023
    Feature Freeze 13/10/23      :milestone, 13-10-2023, 0d
    Test & Bug Fixing            :a3, 13-10-2023, 06-11-2023
    Release Freeze 06/11/23      :milestone, 06-11-2023, 0d
    Release                      :a4, 06-11-2023, 08-12-2023
    Release 08/12/23             :milestone, 08-12-2023, 0d
    
    section Release v24.02
    Feature Definition           :b1, 10-10-2023, 30-10-2023
    Feature Ready 30/10/23       :milestone, after b1, 0d
    Feature Work                 :b2, after b1, 08-12-2023
    Feature Freeze 08/12/23      :milestone, after b2, 0d
    Test & Bug Fixing            :b3, after b2, 26-01-2024
    Release Freeze 26/01/24      :milestone, after b3, 0d
    Release                      :b4, after b3, 23-02-2024
    Release 23/02/24             :milestone, after b4, 0d
```

### Related code

```
gantt
    title Next Release Cycles
    dateFormat  DD-MM-YYYY
    todayMarker off
    
    section Release v23.12
    Feature Definition           :a1, 15-07-2023, 07-08-2023
    Feature Enhancement 07/08/23 :milestone, after a1, 0d
    Feature Work                 :a2, 07-08-2023, 13-10-2023
    Feature Freeze 13/10/23      :milestone, 13-10-2023, 0d
    Test & Bug Fixing            :a3, 13-10-2023, 06-11-2023
    Release Freeze 06/11/23      :milestone, 06-11-2023, 0d
    Release                      :a4, 06-11-2023, 08-12-2023
    Release 08/12/23             :milestone, 08-12-2023, 0d
    
    section Release v24.02
    Feature Definition           :b1, 10-10-2023, 30-10-2023
    Feature Ready 30/10/23       :milestone, after b1, 0d
    Feature Work                 :b2, after b1, 08-12-2023
    Feature Freeze 08/12/23      :milestone, after b2, 0d
    Test & Bug Fixing            :b3, after b2, 26-01-2024
    Release Freeze 26/01/24      :milestone, after b3, 0d
    Release                      :b4, after b3, 23-02-2024
    Release 23/02/24             :milestone, after b4, 0d`
```

## What

- [x] the [mermaid plug-in](https://docusaurus.io/docs/next/markdown-features/diagrams) is needed -> install it
- [x] Configure the plug-in if needed (textsize and themeing)
- [x] Add provided code to the specific section
- [x] Check content if every information is included

**Comment by SebastianBezold** [comment]
HI @stephanbcbauer,

yeah, highly appreciated, if we could have diagrams as code instead of binary images!
AFIK, Mermaid is not a plain Markdown feature. On GitHub, it is automatically rendered, but i guess we would need a plugin for it to work in Docusaurus. Should be easy to try it out locally for verification

**Comment by stephanbcbauer** [comment]
> HI @stephanbcbauer,
> 
> yeah, highly appreciated, if we could have diagrams as code instead of binary images! AFIK, Mermaid is not a plain Markdown feature. On GitHub, it is automatically rendered, but i guess we would need a plugin for it to work in Docusaurus. Should be easy to try it out locally for verification

THX @SebastianBezold plug-in is needed. But easy to install. Be careful, because we are using an old version of docusarus, also the plug-in needs to be version 2.2.0

**Comment by SebastianBezold** [comment]
> > HI @stephanbcbauer,
> 
> > 
> 
> > yeah, highly appreciated, if we could have diagrams as code instead of binary images! AFIK, Mermaid is not a plain Markdown feature. On GitHub, it is automatically rendered, but i guess we would need a plugin for it to work in Docusaurus. Should be easy to try it out locally for verification
> 
> 
> 
> THX @SebastianBezold plug-in is needed. But easy to install. Be careful, because we are using an old version of docusarus, also the plug-in needs to be version 2.2.0

Yeah the old docusuarus version is still used because the openapi plugin is not compatible with newer releases (#130). Hope the plug-in we choose for mermaid support does not come with the same "features" :)

**Comment by stephanbcbauer** [comment]
PR is already merged. Diagramm is visible. For sure, we could work on the visualization/theming. But the issue can be closed
