### ISSUE TITLE
feat(doc): Adapt the way of displaying diagramms

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#410]
## What

- [ ] Find a general way to present diagramms in a better way than it is right now
- [ ] Optional: Add some theming -> It doesent look so nice (like the other content)

## Why

The release diagramm (created with mermaid), which is published [here](https://eclipse-tractusx.github.io/release-information#the-next-two-release-cycles-in-detail) is a good starting point related to (future) TRG 1.04 #401 

Hower the diagramm is too small. There should be the possibility to zoom in (like on GitHub) or maybe to theme it.

<img width="779" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/325c2fff-1464-4fae-87bb-85cc398fe008">

**Comment by carslen** [comment]
Docusaurus 2.2.0 (the version we use) supports mermaid diagramms: https://docusaurus-archive-october-2023.netlify.app/docs/2.2.0/markdown-features/diagrams

BTW: Is the [page you've linked](https://eclipse-tractusx.github.io/release-information/#the-next-two-release-cycles-in-detail) accessible via any menu of the website?

Looking for volunteers to implement it on our website.

**Comment by stephanbcbauer** [comment]
It can be closed. We are supporting mermaid. Also, SVG based on draw.io are possible. The diagram was replaced by [timeline.](https://github.com/orgs/eclipse-tractusx/projects/26/views/35)
