### ISSUE TITLE
TEST GE Feature

### ISSUE THREAD

**Issue by gabyertl** [eclipse-tractusx/eclipse-tractusx.github.io#416]
Test User Story Tractus X - GabyErtl 
Ergänzung - Test

**Comment by FaGru3n** [comment]
Hi @gabyertl could we close this issue?

**Comment by gabyertl** [comment]
This was a test issue

**Comment by gabyertl** [comment]
Hi Fabian,

Closed.
Bitte check, ob korrekt …

Danke,
LG Gaby

Mag. Gabriele Ertl, MSc
Principal Business Process Consultant,
Enterprise Architect, Project Manager
Business Transformation Services

SAP Oesterreich GmbH,
Lassallestraße 7b, A-1021 Wien

T       +43-1-28822-75233
M      +43-664-6207354
The content of this e-mail and of any attached documents is exclusively provided for informational purposes.
E-mails, contract drafts and any offers of SAP shall be non-binding, unless expressly provided differently in writing. In particular, cost estimates of SAP shall be non-binding, unless the parties agree differently and in writing.
Commercial Register-No.: FN 80230 k
Commercial Court Vienna
