### ISSUE TITLE
Move Traceability Video to Largefiles Repository

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/eclipse-tractusx.github.io#420]
Currently, this repository contains a video included in the traceability kit:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/static/video/traceability-video-9min-UT.mp4

As discussed in #195, this should be moved into the largefiles repository:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles

**Comment by FaGru3n** [comment]
- added documentation how to store large files in a different repository.

@mhellmeier do you know someone from Tracability Kit who can adapt these the changes, or even we can communicate with someone?

**Comment by mhellmeier** [comment]
Yes, I can do it!

**Comment by mhellmeier** [comment]
Video moved and fixed in #499
