### ISSUE TITLE
Story "Extend Catena-X Standards with SHACL-Descriptions of Graph Assets"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/eclipse-tractusx.github.io#431]
# Story "Extend Catena-X Standards with SHACL-Descriptions of Graph Assets"

Repository https://github.com/eclipse-tractusx/eclipse-tractusx.github.io

## Statement 

As a Catena-X stakeholder, I want to have a standard for describing graph assets which allows me to describe the actual shape/content of a graph in a fashion that could be used to drive a meta-computation.

## Acceptance Criteria

- standard CX-0084 extended
- optionally CX-0067 extended
- descriptions of examples in both the standard and the kit

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/283#issuecomment-1770550971_

**Comment by TomBuchertTSystems** [comment]
Assignee: Oz
