### ISSUE TITLE
# Story "Build a Blueprint with an Example Set of Assets and a Skill Demonstrating Goal-Oriented Computations"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/eclipse-tractusx.github.io#433]
# Story "Build a Blueprint and an Example Set of Assets and a Skill Demonstrating Goal-Oriented Computations"

Repository https://github.com/eclipse-tractusx/eclipse-tractusx.github.io

## Statement 

As a Graph or Skill Asset developer/deployer, I want to have a blueprint and realistic example which shows me how to encode a goal-oriented skill such that I can adopt this for my own use case.

## Acceptance Criteria

- blueprint with SPARQL snippets containing
           - set of asset descriptions
           - ready-made skill

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/283#issuecomment-1770555738_

**Comment by igorsvetlov** [comment]
Blueprint with  SPARQL snippets  containing 

- set of asset descriptions
- ready-made skill

**Comment by TomBuchertTSystems** [comment]
Assigne: Oz
