### ISSUE TITLE
# Story "Document Some Important Features in the Agent Kit"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/eclipse-tractusx.github.io#434]
# Story "Document Some Important Features in the Agent Kit"

Repository https://github.com/eclipse-tractusx/eclipse-tractusx.github.io

## Statement 

As a KA developer, I want to have documented examples for important standard features, such as remote skill invocation, aggregation and dealing with the catalogue such that I can make use of them in my creation and invocation of skills.

## Acceptance Criteria

- Example for the invocation of remote skills in both distribution/run modes
- Example for aggregating (in subselects)
- Example for binding against the catalogue

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/283#issuecomment-1770561413_

**Comment by TomBuchertTSystems** [comment]
Support by Oz

**Comment by drcgjung** [comment]
ProStep Paper verlinken.
