### ISSUE TITLE
Guideline for Use Case Development with KA - Roles & responsibilities

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/eclipse-tractusx.github.io#437]
As a developer of a new use case with a KA application I want to know which steps I need to do in order to have a running application in Catena-context. The guideline shall answer the following questions:

- What are the relevant stakeholders to consider when building a new KA application? What do they need at what time?-->Review also existing personas if they still fit or if they need to be revised.
- Which qualification is necessary to develop a KA application?

Acceptance Criteria:
- Use Case Diagram with main tasks/responsibilities & some basic description of every actor

Estimation: 
- 7

**Comment by TomBuchertTSystems** [comment]
Assignees: Rolf, Jörg, Tom

**Comment by bosserf** [comment]
first working session Jörg&Rolf on 10 November
