### ISSUE TITLE
Guideline for Use Case Development with KA - Process

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/eclipse-tractusx.github.io#438]
As a developer of a new use case with a KA application I want to know which steps I need to do in order to have a running application in Catena-context. The guideline shall answer the following questions:

- What are necessary constraints and prerequisites to use KA?
- What is the logical sequence of steps when developing a new application?

Acceptance Criteria:

- Process diagram including steps for developing new use case/application
- Responsibilities/swimlanes
- Necessary Information objects

Estimation: 
- 7

**Comment by TomBuchertTSystems** [comment]
Assignees: Rolf, Jörg, Tom

**Comment by drcgjung** [comment]
Miro board link: https://miro.com/app/board/uXjVNOW-o0E=/ Password: knowledge

**Comment by drcgjung** [comment]
its done
