### ISSUE TITLE
Update main navigation (KIT) subnavigation

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/eclipse-tractusx.github.io#441]
Hi - please change the wording of one navigation item in the sub-navigation of KITS.
There is now a sub-navigation item named "preview". Please change it to "Upcoming KITs".

Thanks!

**Comment by manojava-gk** [comment]
PR created. - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/445
