### ISSUE TITLE
docs(e2e adopter journey): Adapt entry statement for tutorials

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#449]
## What

[Why tutorials](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials.md) needs more content to describe what the tutorials are for. What is the initial idea.

## Why

tbd

## Tasks

- [x] Meeting with Felix and/or Daniel
- [x] Content added

**Comment by gerbigf** [comment]
I've shortened the intro to tutorials and formulated proper sentences. I don't think that we need more content on the generic "tutorials" - everyone knows what tutorials are and we aren't special. A very precise description of the what, for whom, why, how of the e2e tutorial is already existing.

**Comment by stephanbcbauer** [comment]
Thx @gerbigf  -> issue can be closed
