### ISSUE TITLE
docs(e2e adopter journey): Check onboarding material

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#453]
## What

The whole chapter needs a review and also the [section](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/inform/onboardingMaterial.md#5-backend-integration) needs to be updated

## Tasks

- [x] Talk to Felix
- [x] Adapt the chapter

**Comment by gerbigf** [comment]
@stephanbcbauer I'll review and finalize the onboarding material.

**Comment by stephanbcbauer** [comment]
@gerbigf  thank you very much for your contribution
