### ISSUE TITLE
docs(e2e adopter journey): Chapter boost adaptation and checks

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#458]
## What

The boost section needs to be checked. The provided cURL command need to be checked and there is also content needed for the consume Data section.

## Tasks

- [x] Qualitycheck and test for the [provideData](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/boost/provideData.md) section
- [ ] Add content to the [consumeData](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/boost/consumeData.md) section

**Comment by SeBuSov** [comment]
Hi @stephanbcbauer ,
we tested the cURLs for provideData section and they all worked.
cc @jkbquabeck
