### ISSUE TITLE
ERROR: unable to create file docs

### ISSUE THREAD

**Issue by klaudiaZF** [eclipse-tractusx/eclipse-tractusx.github.io#493]
I am trying to add Security Guidelines to Eclipse site, but I'm facing issue with git cloning.
I'm using Windows.

<img width="960" alt="gitcloning" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/148344761/0f2c3bf7-1c26-4738-ad31-6b01d9e4a711">

**Comment by klaudiaZF** [comment]
@FaGru3n Hi Fabian, sorry to bother you, but maybe you know who can be helpful with this issue?

**Comment by FaGru3n** [comment]
I guess this looks like there is a little problem with your git config.

Maybe `git config --global core.longpaths true` or some similar windows cmd will work. see for example https://github.com/dart-lang/pub/issues/3803

**Comment by klaudiaZF** [comment]
it worked! thanks :)
