### ISSUE TITLE
Enable branch protection for our web-page

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/eclipse-tractusx.github.io#515]
> I want to highlight the importance of reviews for our community. Since we are the biggest project in the Eclipse foundation and we already discussed the maintenance of overarching repositories like the Docusaurus instance of eclipse-tractusx.github.io previously in the mail discussion, checks are essential to continue with high-quality outcomes.
>  
> At this year's EclipseCon, they highly suggested reviewing every pull request by at least two reviewers. Since Tractus-X aligned for at least one reviewer, I wish that we take this decision as the absolute minimum! During the last time, I saw different pull requests directly merged from the same person without any review or pull requests without any information in it (description) or with removed checkboxes of the standard template. Even if the changes are minor, everything should be communicated clearly and checked by at least one person.
>  
> Different Examples (no fingerpointing, just to show what I am talking about):
> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/490
> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/513
> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/476
> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/474
> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/463
>  
>  
> Hope you are going for the same opinion. Otherwise, I am happy to discuss it here.
>  
> Thanks, and have a great week
> Malte
>

**Comment by almadigabor** [comment]
I guess we can close this one, right @FaGru3n?

**Comment by mhellmeier** [comment]
Yes, thats already done in the linked PR.

Maybe we could create a new issue for the Codeowner file as discussed here: https://github.com/eclipse-tractusx/.eclipsefdn/pull/43#discussion_r1410429486

**Comment by FaGru3n** [comment]
Hi @almadigabor jep issue can be closed sorry for missed mentioning part for this issue.

@mhellmeier Jep seems a good idea to reference all information to our codeowners file into a new issue. 😉
