### ISSUE TITLE
fix(tutorials): delete one "empty" policy

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#560]
## What

The [E2E adopter Journey tutorials](https://eclipse-tractusx.github.io/docs/tutorials/e2e/) provides some policies in the provide Data Section. In this section, two “empty” (with no constraints) policies are created. One of them should be deleted or adapted with some constraints.

- [First](https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/provideData#request-catalog---second-try)
- [Second](https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/provideData#create-first-contract-definition)

Even if the first one is an access and the second one a usage policy… I think it's just confusing

## Why

The current situation is more confusing than helping

## Note

Please keep in mind to check the whole workflow, if you chnage something

**Comment by stephanbcbauer** [comment]
@awellnitz-materna please have a look. Because i think something was also changed in your PR #570 ?

**Comment by awellnitz-materna** [comment]
> @awellnitz-materna please have a look. Because i think something was also changed in your PR #570 ?

Exactly, we have adapted that too.
Only 2 are created here and they are not empty anymore.

**Comment by stephanbcbauer** [comment]
> > @awellnitz-materna please have a look. Because i think something was also changed in your PR #570 ?
> 
> Exactly, we have adapted that too. Only 2 are created here and they are not empty anymore.

Awesome... i added the Closes tag in the related PR thx
<img width="119" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/bc862ca9-f1fa-47f1-8bc3-886c19994aee">
