### ISSUE TITLE
[KIT Digital Twin] Update to Operating Model V2.1

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-tractusx/eclipse-tractusx.github.io#568]
A new version of the Catena-X Operating Model was published: 

https://catena-x.net/fileadmin/user_upload/Publikationen_und_WhitePaper_des_Vereins/CX_Operating_Modelv2.1_final.pdf 

it contains now the information about the decentralized digital twin registry etc. So it should be the basis for the Digital Twin KIT.

Context: https://eclipse-tractusx.github.io/docs-kits/kits/Digital%20Twin%20Kit/Adoption%20View%20Digital%20Twin%20Kit#customer-journey

**Comment by carslen** [comment]
Has this been solved with PR #654 ?

**Comment by arnoweiss** [comment]
Good catch
