### ISSUE TITLE
docs introduce `.github/CODEOWNERS` for eclipse-tractusx/eclipse-tractusx.github.io

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/eclipse-tractusx.github.io#576]
As this PR is not introduceing branch protection and required review count to the GH Org but to the eclipse-tractusx/eclipse-tractusx.github.io repo only, I would like to require 2 reviewers. For this repository enough stakeholders should be available doing reviews. 

Maybe we should also think about to introcude `.github/CODEOWNERS` (for eclipse-tractusx/eclipse-tractusx.github.io). Code owners are automatically assigned to new PRs:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

_Originally posted by @carslen in https://github.com/eclipse-tractusx/.eclipsefdn/pull/43#discussion_r1410429486_

**Comment by SebastianBezold** [comment]
IMHO, `CODEOWNERS` won't add a lot of value or improvement to our current collaboration workflow.
Currently it is as follows:
- Everyone can open a PR (contribute)
- Before being able to merge, TWO approvals from reviewers are required
- The approvals have to be given by people with the committer role
- Only committers can merge an approved PR

Potential things a `CODEOWNERS` file could be used for:
- Path specific permissions (i.e. /docs/release or KITs)
- Auto-Assign reviewers on new PRs

Things that we are limited in my opinion:
- We do only have a committer group, so assigning permissions on group level might be difficult (individual assignments would be needed i guess)

**Comment by mhellmeier** [comment]
I would vote for a `CODEOWNERS` file. Especially for the KITs, there are some specific persons and responsibilities.

If someone creates a PR or an Issue for your KIT, you as a KIT developer don't get information that someone wants to change your KIT. You could subscribe to the repository, but in this case, you get notifications for every PR and Issue. Thus, a `CODEOWNERS` file would be beneficial.

**Comment by arnoweiss** [comment]
I think `CODEOWNERS` could help on the margins but I don't expect any big changes for the challenges we have. Would be open for a PR (and to be responsible for the DT Kit) though.

**Comment by FaGru3n** [comment]
will close this issue but the general idea seems still valid at least from my perspective.
