### ISSUE TITLE
fix(tutorials): Prerequisites Terraform - malformed shell command

### ISSUE THREAD

**Issue by DaEwe** [eclipse-tractusx/eclipse-tractusx.github.io#577]
This is not working:
`sudo wget -o - https://apt.releases.hashicorp.com/gpg | | sudo gpg --dearmor -o | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
`

**Comment by stephanbcbauer** [comment]
@JohannesARENA2036 could you please have a look? i thought it worked at the community days?

**Comment by JohannesARENA2036** [comment]
Done, correct command entered:  

 `sudo wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring`
