### ISSUE TITLE
[KIT Digital Twin] Sequence Diagram should be readable

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-tractusx/eclipse-tractusx.github.io#585]
Graphic https://eclipse-tractusx.github.io/assets/images/DTKIT_discovery_seq-1bdc771bb6d7dbc8fda0e9b71946113d.svg, the sequence diagram, is very hard to read but referred to in different tables. Either split sequence diagram or provide it in better quality.

Best way would be to provide them in PlantUML

**Comment by arnoweiss** [comment]
They're currently rendered from mermaid. I'll split them up in the next release.

**Comment by danielmiehle** [comment]
@BirgitBoss @arnoweiss : can we close this ticket we the R24-03?

**Comment by BirgitBoss** [comment]
Graphic was split so issue can be closed
