### ISSUE TITLE
Broken link to calendar ICS file

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/eclipse-tractusx.github.io#619]
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/d789b216e1f3f5cb5aaa498854db750463a54414/community/open-meetings.mdx#L13

On the rendered website the link to the calendar ICS file is broken; links to https://eclipse-tractusx.github.io/community/meetings/alignment-and-planning-trace-x.ics. Working link is https://eclipse-tractusx.github.io/meetings/alignment-and-planning-trace-x.ics

//CC @stephanbcbauer

**Comment by stephanbcbauer** [comment]
Thank you very much for this issue. We should find a fix for it. Propably just using 

```
meetingLink="/meetings/alignment-and-planning-trace-x.ics" 

instead of 

meetingLink="../meetings/alignment-and-planning-trace-x.ics" 
```
