### ISSUE TITLE
bug: cloning repository has problems (long filenames, special characters)

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/eclipse-tractusx.github.io#646]
### Current Behavior

When cloning the repository, there are some warnings and fatal errors during the cloning process:
```
Cloning into 'eclipse-tractusx.github.io'...
remote: Enumerating objects: 87775, done.
remote: Counting objects: 100% (7096/7096), done.
remote: Compressing objects: 100% (1128/1128), done.
remote: Total 87775 (delta 3315), reused 6838 (delta 3096), pack-reused 80679
Receiving objects: 100% (87775/87775), 226.82 MiB | 8.12 MiB/s, done.
Resolving deltas: 100% (43422/43422), done.
error: unable to create file docs-kits_versioned_docs/version-23.09/kits/Digital Twin Kit/Software Development View/API EDC Discovery/post-list-of-bpns-or-an-empty-array-to-retrieve-available-company-connector-authorization-required-roles-view-connectors.api.mdx: Filename too long
error: unable to create file docs-kits_versioned_docs/version-23.12/kits/Digital Twin Kit/Software Development View/API EDC Discovery/post-list-of-bpns-or-an-empty-array-to-retrieve-available-company-connector-authorization-required-roles-view-connectors.api.mdx: Filename too long
Updating files: 100% (1971/1971), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

### Expected Behavior

Clone should work on all operating systems without warnings and errors.

### Steps To Reproduce

Just clone the repository (in this example on windows).

Based on [current discussions](https://stackoverflow.com/questions/24898680/fatal-unable-to-checkout-working-tree), the "fatal: unable to checkout working tree" may be caused by file names containing special characters that doesn't work with Windows.

Further, long file names like `post-list-of-bpns-or-an-empty-array-to-retrieve-available-company-connector-authorization-required-roles-view-connectors.api.mdx` should be avoided since they cause a "Filename too long" error.

**Comment by carslen** [comment]
Hm, maybe @arnoweiss can help out here and check if these kind of long file names are necessary?

**Comment by arnoweiss** [comment]
Never observed this. The mdx files are gonna be taken out and moved to swaggerhub until R24-5
