### ISSUE TITLE
Ensure up-to-date `DEPENDENCIES` file

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io#655]
## Description

We want to ensure, that our `DEPENDENCIES` file is up-to-date. This is anyways part of our legal due diligence.
This process should be as automated as possible.

## Acceptance Criteria

- [ ] Automated hint on contributions, that the `DEPENDENCIES` file is out of date

**Comment by FaGru3n** [comment]
+2 👍🏼 so guess could be merged
