### ISSUE TITLE
Remove remote-content plugin for openAPI specs

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io#671]
## Description

We currently have a lot of `docusaurus-plugin-remote-content` entries in our docusaurus config: see https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/docusaurus.config.js#L122

This will pull in content on build time and therefore updates do happen in an uncontrolled way. Any contribution regardless of where it is made, will build the page and update the contents configured through that plugin.

Also, some openAPI specs are even pull from apps running on consortia infra. I don't known how anyone can be sure which version is running there and if it is the right one to show on the website

## Proposed change

Remove the remote content plugin completely and update contents in a controlled fashion.

**Comment by carslen** [comment]
eclipse-tractusx/sig-infra#376

**Comment by SebastianBezold** [comment]
This won't be done by the System Team anymore.
