### ISSUE TITLE
Create Business Partner kit page, based in the ./docs folder

### ISSUE THREAD

**Issue by santiagoejm** [eclipse-tractusx/eclipse-tractusx.github.io#68]
Currently the Business Partner Kit is created as a react Page, this content should be displayed as a document page, the link structure should follow the next one:

- .docs/kits/BusinessPartnerKit:
  - /adoption-view.md
  - /software-operation-view.md
  - /documentation.md
  - /software-development-view/
    - specific.md
    - ...Generated documentation for end-points

2 plugins should be installed:
- [https://github.com/rdilweb/docusaurus-plugin-remote-content](https://github.com/rdilweb/docusaurus-plugin-remote-content) to bring remote documentation.
- [https://github.com/PaloAltoNetworks/docusaurus-openapi-docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) to generate Documentation from `.yaml` files

**Comment by maximilianong** [comment]
@santiagoejm can you change the order - it should be:
1. adoption view
2. software operation view
3. software development view
4. documentation 

but anything else is fine for me, thanks!

**Comment by santiagoejm** [comment]
@maximilianong I wouldn't recommend to put the Software operation view as a second item, this is a dropdown menu with a bunch of items that once open will take out of view the last one (documentation in this case). There is a particular reason why software development view shouldn't be the last one?

**Comment by maximilianong** [comment]
@santiagoejm sorry - you are absolutely right.
