### ISSUE TITLE
Broken `Adoption View` link

### ISSUE THREAD

**Issue by SebastianOpriel** [eclipse-tractusx/eclipse-tractusx.github.io#689]
Link [here](https://eclipse-tractusx.github.io/docs-kits/kits/Traceability%20Kit/Software%20Development%20View/Data%20Provider%20Development%20View%20Traceability%20Kit/#edc-policies) pointing to `Adoption View` is broken.

**Comment by mhellmeier** [comment]
Thanks for the hint, but the broken links on different parts have already been addressed (duplicate of #639).
