### ISSUE TITLE
Add method icons to the `sidebar` generated .mdx files

### ISSUE THREAD

**Issue by santiagoejm** [eclipse-tractusx/eclipse-tractusx.github.io#75]
When apply, all of the end points generated with the [plugin](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) should display in the `sidebar` navigation the Method (GET, PUT, POST...) that they point to. like the example:

![Screenshot 2023-01-20 at 15 46 51](https://user-images.githubusercontent.com/68547995/213726819-cf866680-d887-4580-9e2c-5bbb029fa758.png)

**Comment by maximilianong** [comment]
Will the controller information also be available? Like it is in Swagger. There you have Controller A and below that all the endpoints.

**Comment by santiagoejm** [comment]
hi @maximilianong, the title of the controller is defined by us, in the name we give to the folder that holds the .mdx files that the plugin generate, in our case for this version we decided to give it the name of `Pool API` to the parent folder. If this `pool.yaml` contains several controllers, we will need to be provided with several .yaml files (one for each controller, instead of one file with different controllers, if that is our case?) and the output is up to us to place it in a folder with the name of the controller we want. Why this? because our plugin analyse and generate documentation from a full file, not parts of it

**Comment by maximilianong** [comment]
First we take it like discussed - all the methods below Pool API folder.
