### ISSUE TITLE
Reduce the number of KIT versions we keep

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/eclipse-tractusx.github.io#800]
## Description

The website build is quite slow currently. See #771.
As indicated in https://github.com/facebook/docusaurus/discussions/3132, the number of versions we keep may have a big impact on build performance.

We need to discuss, if we can reduce the number of KIT versions we keep.
Keeping "Next" and the two most recent versions could be a good fit IMHO.

If we decide to lower the number of versions we keep, we need to remove the old ones

## Additional thoughts

There are examples of Docusaurus usage with versioning, where very old versions are still shown, but moved to an "archive" instance.

**Comment by arnoweiss** [comment]
@SebastianBezold - do you see any blockers for this?
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/912

**Comment by SebastianBezold** [comment]
Hi @arnoweiss,

no, I don't see any blockers
