### ISSUE TITLE
Use depricated link in Product list

### ISSUE THREAD

**Issue by okamototk** [eclipse-tractusx/eclipse-tractusx.github.io#847]
In following page:

https://eclipse-tractusx.github.io/community/products/

Trace-X description have this link:
  https://github.com/eclipse-tractusx/traceability-foss-backend

**But repositoy haven't been having update more than 1 year.**
Currently, following repository seems used as development repository.

https://github.com/eclipse-tractusx/traceability-foss

Please update Trace-X repository link.

**Comment by SebastianBezold** [comment]
HI @okamototk,

thanks for spotting. You are right, the data used to render the product overview does not seem to be actively updated by the teams. I fixed the Trace-X link in #851 

@danielmiehle, @Siegfriedk @stephanbcbauer: I think this shows, that we either need to automate this, find dedicated maintainers, or remove the product overview, if we cannot keep it up to date. What do you think?
Automation could be done via [release dashboard](https://eclipse-tractusx.github.io/sig-release/). There, we are anyways reading product metadata. Maybe we should open a discussion for that topic

**Comment by Siegfriedk** [comment]
@SebastianBezold weird anyway that the page exists as it does; Who decided on the products?!

**Comment by SebastianBezold** [comment]
> @SebastianBezold weird anyway that the page exists as it does; Who decided on the products?!

Not really sure. @maximilianong, do you have background info in that. I only moved the page ones as we created the "Community" top-level nav. Cannot remember, where I moved it from and who created the initial data

**Comment by maximilianong** [comment]
Its beed a while. I think this page was a requirement that got initiated in combination with the release management but Im not sure. @danielmiehle has the background info here. Lets wait for his feedback what to do with the page :) But anyway, thanks @SebastianBezold for fixing!

**Comment by danielmiehle** [comment]
We initially created the products based on the products in the consortium. If there are any changes or another bundling of the repos makes more sense, we are happy to adapt the page.

**Comment by SebastianBezold** [comment]
Ok so background seems to be clear. I think the problem is, that no one feels responsible for keeping this up to date. So from my point of view we could either get rid of the products overview, since misleading info can be worse than none (we still have the TRG checks dashboard with a product list), or automate the whole info gathering.
