### ISSUE TITLE
Creating a News Entry for Release 24.05

### ISSUE THREAD

**Issue by HFocken** [eclipse-tractusx/eclipse-tractusx.github.io#903]
Please create a news entry to summarize the TX Release 24.05:

Headline: Tractus-X 24.05 available now

We are excited to announce the release of [Tractus-X 24.05](https://eclipse-tractusx.github.io/CHANGELOG)! This release builds the foundation for one of the most significant updates to our Catena-X ecosystem to date. Highlights include an update to the [Multi-Opco solutions](https://www.youtube.com/watch?v=DFC_raxgzog&t=249s), the full implementation of the [Industry Core KIT](https://www.youtube.com/watch?v=Ta83xNfARLE&t=10s) as well as the advancement of [Self Sovereign Identity concepts](https://www.youtube.com/watch?v=8JnGbCWIJZk&t=1s), e.g. Multi-Wallet solutions. Conjointly, it makes several improvements to the user-friendliness of KITs based on feedback received to date, making Tractus-X overall more accessible and welcoming to newcomers and veterans alike. A big thank you to all contributors and committers for bringing this milestone to life and keep Tractus-X as one of the most significant OS projects in the automotive industry.

With Release 24.05, the Catena-X Association will also introduce significant advancements in its operating model including an update to its regulatory framework, an update to its roles, improvements to the overall release management and compatibility schemes as well as for the first time, interoperability criteria. Stay tuned for an official release on the [Catena-X website](https://eclipse-tractusx.github.io/CHANGELOG) at the end of June 2024.

Enjoy diving into the all new Tractus-X Release!

**Comment by RolaH1t** [comment]
News entry text fine for me / yet: URLs not crosschecked
No changes requested ;-)

**Comment by jSchuetz88** [comment]
Created a PR (#907)
