### ISSUE TITLE
[Industry Core KIT] Links to OpenAPI specification for Unique ID Push API are broken

### ISSUE THREAD

**Issue by markuskeidl** [eclipse-tractusx/eclipse-tractusx.github.io#998]
### Current Behavior

Both links to the OpenAPI specification of the Unique ID Push API are broken on page https://eclipse-tractusx.github.io/docs-kits/kits/Industry%20Core%20Kit/Software%20Development%20View/Digital%20Twins%20Development%20View%20Industry%20Core%20Kit#backend-data-service-to-process-unique-id-push-notifications. After clicking on these links you land on the "Page Not Found" page. 

### Expected Behavior

Both links should forward you to the corrent OpenAPI specification in the Industry Core "openapi" folder. These should be the correct links:

- Link to 2.0.0: https://eclipse-tractusx.github.io/docs-kits/kits/Industry%20Core%20Kit/openapi/unique-id-push.yaml
- Link to 2.1.0: https://eclipse-tractusx.github.io/docs-kits/kits/Industry%20Core%20Kit/openapi/unique-id-push_2-1-0.yaml

Or something like that. Not sure how openapi and yaml files are published on the eclipse-tractusx Website.

### Steps To Reproduce

- Navigate to page https://eclipse-tractusx.github.io/docs-kits/kits/Industry%20Core%20Kit/Software%20Development%20View/Digital%20Twins%20Development%20View%20Industry%20Core%20Kit#backend-data-service-to-process-unique-id-push-notifications (Industry Core KIT, Release 24.05). 
- Click on one of the two links in section "The standardized version of this API is [2.0.0](https://eclipse-tractusx.github.io/openApi/industrycore/unique-id-push.yaml). Version [2.1.0](https://eclipse-tractusx.github.io/openApi/industrycore/unique-id-push_2-1-0.yaml) is not (yet) standardized, but backwards compatible, and extends v2.0.0 with the Connect-to-Child feature."
  - Link to 2.0.0: https://eclipse-tractusx.github.io/openApi/industrycore/unique-id-push.yaml
  - Link to 2.1.0: https://eclipse-tractusx.github.io/openApi/industrycore/unique-id-push_2-1-0.yaml
- You will land on the "Page Not Found" page.

**Comment by mhellmeier** [comment]
Links are fixed and will work in the upcoming release (24.08).
